version: '3'

services:
  hello:
    build: .
    ports:
      - "4000:4000"
    networks:
      - "hello"
  redis:
    image: "redis"
    networks:
      - "hello"

networks:
  hello:

volumes:
  workshop_data:

